### ISSUE TITLE
segfault on opening

### ISSUE THREAD

**Issue by JCDetwiler** [lwindolf/liferea#1218]
I'm seeing a new segfault that happens right when starting Liferea.

```
~ liferea
[1]    9145 segmentation fault (core dumped)  liferea
```

The segfault happens inside of malloc, and the gdb backtrace is massive, but here is the most relevant part of the trace:

```
#0  _int_malloc (av=av@entry=0x7ffff1a49aa0 <main_arena>, bytes=bytes@entry=128) at malloc.c:3974
#1  0x00007ffff19068ed in __GI___libc_malloc (bytes=bytes@entry=128) at malloc.c:3305
#2  0x00007ffff1907079 in __GI___libc_realloc (oldmem=<optimized out>, bytes=bytes@entry=128) at malloc.c:3394
#3  0x00007ffff1b9fad1 in g_realloc (mem=<optimized out>, n_bytes=128) at ../glib/glib/gmem.c:201
#4  0x00007ffff1bbec23 in g_string_expand (string=string@entry=0x555555703df0, len=len@entry=64) at ../glib/glib/gstring.c:92
#5  0x00007ffff1bbeca1 in g_string_sized_new (dfl_size=2) at ../glib/glib/gstring.c:123
#6  0x00007ffff1b817c3 in g_build_path_va (separator=0x7ffff1c6004b "/", first_element=0x555557b71710 "/home/jade/.cache/liferea", args=0x7fffff7ff160, str_array=0x0) at ../glib/glib/gfileutils.c:1897
#7  0x00007ffff1b81fb9 in g_build_filename_va (str_array=0x0, args=0x7fffff7ff160, first_argument=<optimized out>) at ../glib/glib/gfileutils.c:2190
#8  g_build_filename (first_element=first_element@entry=0x555557b71710 "/home/jade/.cache/liferea") at ../glib/glib/gfileutils.c:2284
#9  0x0000555555573a3f in common_init_paths () at tests/../common.c:81
#10 0x0000555555573b2d in common_create_config_filename (filename=0x5555555be1a9 "liferea.css") at tests/../common.c:115
#11 common_init_paths () at tests/../common.c:89
#12 0x0000555555573b2d in common_create_config_filename (filename=0x5555555be1a9 "liferea.css") at tests/../common.c:115
#13 common_init_paths () at tests/../common.c:89
```

Seeing some memory leaks too, but `valgrind --fair-sched=yes liferea` for example still yields the segfault.

I remember using Liferea in the past few days or so, but I'm not sure when it stopped working. I most recently upgraded my kernel to 6.2.8 and nvidia driver to 530.41.03. Today, I also finally removed `ibt=off` from my kernel parameters since [the proprietary driver finally supports IBT][1].

Is this just a me problem, or do some of these most recent updates in the Arch repos break Liferea's dependencies?

[1]: https://bugs.archlinux.org/task/74891#comment216588

**Comment by sunwire** [comment]
See https://github.com/lwindolf/liferea/issues/1217

**Comment by JCDetwiler** [comment]
> See #1217

Oops, search didn't turn up anything when I looked for "segfault." My bad.
