### ISSUE TITLE
Gets stuck while updating FreshRSS feeds

### ISSUE THREAD

**Issue by Nosen92** [lwindolf/liferea#1273]
The update pauses indefinitely at `Updating (16/217)...`
I'm new to this software. Running fresh install of 1.14.5 rpm on Fedora 38.
I added my FreshRSS instance as source.
`http://[EXTERNALIP:PORT]/api/greader.php`
Provided user and api password.

In the console i get this output:
```
Traceback (most recent call last):
  File "/usr/lib64/liferea/plugins/gnome-keyring.py", line 63, in do_store
    coll = self.get_collection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/liferea/plugins/gnome-keyring.py", line 41, in get_collection
    service = Secret.Service.get_sync(Secret.ServiceFlags.LOAD_COLLECTIONS, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: No such secret item at path: /org/freedesktop/secrets/collection/login/24 (19)
sys:1: Warning: g_string_insert_len: assertion 'string != NULL' failed
```

Liferea finds and displays my feeds in my folders correctly.
Updating the content in those feeds gets stuck though. Unsure about how to proceed.

**Comment by lwindolf** [comment]
Sorry that I did not yet look into this. Will try to reproduce it soon.

**Comment by lwindolf** [comment]
@Nosen92 Thinking about what could cause your problem, judging from the error message it looks like the Liferea keyring is not being returned from libsecret.

Can you please check using `seahorse` wether there is a "liferea" keyring and wether you can unlock it and if you see secrets inside?

If there is such a keyring you can safely delete it in `seahorse`then restart Liferea and it will be recreated (of course reasking you for all passwords).

**Comment by lwindolf** [comment]
I've fixed some issues in fb7683305fca659404c2dbc11fc5b0dbba54d472 and e69b495c8d382d148e9ca1327d9f12543c55a8df

I know it has been a long time: if you are still using Liferea could you retest?
