### ISSUE TITLE
Internal Browser not working

### ISSUE THREAD

**Issue by r00t9** [lwindolf/liferea#1331]
I try to open internal tab it don't show anything 

$ liferea --debug-conf

```
CONF   : proxy auto detect is configured
CONF   : Manual proxy settings are now NULL:0 NULL:NULL
CONF   : Scheduling feedlist save
sys:1: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
Traceback (most recent call last):
  File "/home/cde/.local/share/liferea/plugins/feedalerts/feedalerts.py", line 41, in on_node_updated
    searchtext=(config['Main']['Search'])
  File "/usr/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'Main'
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0

(liferea:10119): Gtk-WARNING **: 10:29:42.525: Theme parsing error: <data>:2:28: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(liferea:10119): Gtk-WARNING **: 10:29:42.525: Theme parsing error: <data>:3:36: The style property GtkButton:default-outside-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(liferea:10119): Gtk-WARNING **: 10:29:42.525: Theme parsing error: <data>:4:25: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(liferea:10119): Gtk-WARNING **: 10:29:42.525: Theme parsing error: <data>:5:30: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(liferea:10119): Gtk-WARNING **: 10:29:42.526: Theme parsing error: <data>:6:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
sys:1: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
```
![liferea](https://github.com/lwindolf/liferea/assets/44726596/65b9d6fc-e0a2-4470-a87a-02035dd62088)

**Comment by lwindolf** [comment]
Do you have an NVidia graphics card? If yes please have a look at the workaround described in #1308

If not can you please try the same URL with the Gnome Web browser? Does it have the same problem?

**Comment by r00t9** [comment]
It was working ok, like 3 weeks ago last time i check. Is a VM so i didn't think to check for this. I test it and is working, sometimes xfce panel not responding it crash :/ 

Thanks and sorry :)

**Comment by lwindolf** [comment]
@r00t9 No problem. I'm glad it works for you.
