### ISSUE TITLE
Can't update FreshRSS feeds

### ISSUE THREAD

**Issue by pyche2** [lwindolf/liferea#1337]
Hi, 

I have a FreshRSS on  my server and I can use it with other apps on linux.

I have a debian 12 and I'm running Liferea 1.14.4. I've checked the issue #1273 but it's not exactly the same problem.

I added my FreshRSS instance as source.
 `https://my.domain/api/greader.php`
Provided user and api password.

If I run liferea as my current user it asks me several times for my username and password and then does nothing.

If I run liferea as sudo it asks me for my username and password, load the folders but  in the console i get this output:

`Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 52, in do_query
    coll = self.get_collection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 41, in get_collection
    service = Secret.Service.get_sync(Secret.ServiceFlags.LOAD_COLLECTIONS, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-exec-error-quark: L’exécution du processus fils « dbus-launch » a échoué (Aucun fichier ou dossier de ce type) (8)
sys:1: Warning: g_uri_escape_string: assertion 'unescaped != NULL' failed
` 

and i can't get the content of the feeds.

If I transform the source as "local subscriptions" everything is working fine.

If I run seahorse as my user I can see the entry liferea, not if I run it as sudo. 

I've tried as you said in the other topic to delete the entry in seahorse and try again but still the same behaviour.

Also i don't know if it's linked or if it's an other issue but if I run liferea as sudo and click on flux -> proprerties in the log i get "Segmentation error" and the app just crashes

**Comment by lwindolf** [comment]
It seems like Liferea is unable to fetch the credential for your FreshRSS login from the secret store. The `q-exec-error-quark` line hints on a `dbus-launch` error. Sadly I know no French.

Can you rerun Liferea with `LANG=C liferea` so the error message is written in English?

Also after this error the credential dialog should pop up. Is (after entering the correct credentials) it possible to access the FreshRSS feeds?

**Comment by lwindolf** [comment]
Also please do not run Liferea with sudo. This will not help in any way!

**Comment by pyche2** [comment]
Thx for your reply,

So if I don't run it with sudo I *had* nothing in the logs. 

But then I've deleted the secret in seahorse. Restarted liferea,  now liferea won't ask me to create the secret again and everytime I try to update there is a pop asking for my name and password and in the logs  : 

`Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 63, in do_store
    coll = self.get_collection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 41, in get_collection
    service = Secret.Service.get_sync(Secret.ServiceFlags.LOAD_COLLECTIONS, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: No such secret item at path: /org/freedesktop/secrets/collection/login/3 (19)`


I've tried to purge liferea, removed all the liferea directories I could find, redownloaded the app but it's still not asking me to create a secret.

I've tried to install the flatpak also  : I can get all the articles on the first connection but when I try to update I have the same pop up showing and the same logs : 

`Traceback (most recent call last):
  File "/app/lib/liferea/plugins/gnome-keyring.py", line 63, in do_store
    coll = self.get_collection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/liferea/plugins/gnome-keyring.py", line 41, in get_collection
    service = Secret.Service.get_sync(Secret.ServiceFlags.LOAD_COLLECTIONS, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: No such secret item at path: /org/freedesktop/secrets/collection/login/3 (19)
`

**Comment by lwindolf** [comment]
Googling a bit it seems to be a problem on the libsecret side (not within Liferea). The keyring is in an useable state. 

     https://unix.stackexchange.com/questions/265503/how-do-i-fix-no-such-secret-collection-at-path-for-gnome-keyring-and-arch-l

Arch Linux seems to have instructions on how to get out of this (see section 6.4)

    https://wiki.archlinux.org/index.php/GNOME/Keyring

On the other hand there is also a problem in Liferea with not coping here and at least asking the password each time...

**Comment by bxb2world** [comment]
I'm having the same problem synchronizing FreshRSS (server https://cheredeprince.net/) on antiX (based on Debian 12 - Bookworm) with version v1.14 of Liferea.

**Comment by lwindolf** [comment]
I can sometimes reproduce a weird login problem.

So in general one at least one login works it is possible to update everything of the FreshRSS source. But often the login dialog reappears all the time the login info does not get saved.

Somehow the persistence is broken. It could have to do with HTTP 301 redirects.

**Comment by lwindolf** [comment]
I've added a banner to clarify in what login state a node source is.

![Image](https://github.com/user-attachments/assets/f089babe-4aa0-4993-b36a-f82b4f9eab60)

This helps understanding the state. It immediately helped me to see that I can update subscriptions of an online account despite it not being logged in. This then causes password asking races.

Fix for this will follow.

**Comment by lwindolf** [comment]
I've fixed some issues in fb7683305fca659404c2dbc11fc5b0dbba54d472 and e69b495c8d382d148e9ca1327d9f12543c55a8df

I know it has been a long time: if you are still using Liferea could you retest?
