### ISSUE TITLE
[Popup Notifications] Traceback

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#198]
While updating feeds:
```
(liferea:8781): libsoup-WARNING **: (soup-uri.c:581):soup_uri_copy: runtime check failed: (SOUP_URI_IS_VALID (uri))
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/libnotify.py", line 35, in on_node_updated
    notification = Notify.Notification.new (nodeTitle)
TypeError: new() takes exactly 3 arguments (1 given)

(liferea:8781): libsoup-WARNING **: (soup-uri.c:581):soup_uri_copy: runtime check failed: (SOUP_URI_IS_VALID (uri))
```

```
(liferea:8781): libsoup-WARNING **: (soup-uri.c:581):soup_uri_copy: runtime check failed: (SOUP_URI_IS_VALID (uri))
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/libnotify.py", line 35, in on_node_updated
    notification = Notify.Notification.new (nodeTitle)
TypeError: new() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/libnotify.py", line 35, in on_node_updated
    notification = Notify.Notification.new (nodeTitle)
TypeError: new() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/libnotify.py", line 35, in on_node_updated
    notification = Notify.Notification.new (nodeTitle)
TypeError: new() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/libnotify.py", line 35, in on_node_updated
    notification = Notify.Notification.new (nodeTitle)
TypeError: new() takes exactly 3 arguments (1 given)

(liferea:8781): libsoup-WARNING **: (soup-uri.c:581):soup_uri_copy: runtime check failed: (SOUP_URI_IS_VALID (uri))
```

**Comment by lwindolf** [comment]
Fixed. Thanks for reporting it.
