### ISSUE TITLE
crash (SIGSEGV) on shutdown

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#201]
Hi,

This crash was reported in the Debian tracker for liferea 1.10.15:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788666

Does it make sense to you?

Original report:
I had a crash and core dump when shutting down liferea:

```
$ gdb -batch -n -ex bt -ex 'thread apply all bt full' --core /var/crash/1000/6933-1000-1000-11-1434004179-chianamo--usr-bin-liferea.core /usr/bin/liferea
[New LWP 6933]
[New LWP 6938]
[New LWP 6937]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `liferea'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000425a47 in feedlist_get_selected () at feedlist.c:217
217 feedlist.c: No such file or directory.
#0  0x0000000000425a47 in feedlist_get_selected () at feedlist.c:217
#1  0x0000000000447649 in liferea_shell_destroy () at liferea_shell.c:1400
#2  0x000000000043141b in on_shutdown (user_data=<optimized out>) at main.c:294
#3  0x00007f6201de3b4d in g_main_context_dispatch (context=0xeabc80) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3122
#4  0x00007f6201de3b4d in g_main_context_dispatch (context=context@entry=0xeabc80) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3737
#5  0x00007f6201de3f20 in g_main_context_iterate (context=context@entry=0xeabc80, block=block@entry=0, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3808
#6  0x00007f6201de3fcc in g_main_context_iteration (context=0xeabc80, context@entry=0x0, may_block=may_block@entry=0) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3869
#7  0x00007f62025b86e1 in g_application_run (application=0xef4230 [GtkApplication], argc=argc@entry=0, argv=argv@entry=0x0) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gapplication.c:2328
#8  0x000000000041b640 in main (argc=1, argv=0x7ffc2c9c4b48) at main.c:262

Thread 3 (Thread 0x7f61f3cdf700 (LWP 6937)):
#0  0x00007f62018b150d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f6201de3ebc in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0xeb52f0, timeout=-1, context=0xeb5360) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:4103
        poll_func = 0x7f6201df33e0 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0xeb52f0
#2  0x00007f6201de3ebc in g_main_context_iterate (context=context@entry=0xeb5360, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3803
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0xeb52f0
#3  0x00007f6201de3fcc in g_main_context_iteration (context=0xeb5360, may_block=1) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3869
        retval = <optimized out>
#4  0x00007f61f3ce728d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#5  0x00007f6201e0a955 in g_thread_proxy (data=0xe9a140) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gthread.c:764
        thread = 0xe9a140
#6  0x00007f6201b850a4 in start_thread (arg=0x7f61f3cdf700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7f61f3cdf700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140058678916864, -3998110244094618693, 0, 140059009171552, 140058915023104, 140058678916864, 3909190935524922299, 3911332960942019515}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f62018ba04d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f61f34de700 (LWP 6938)):
#0  0x00007f6202583384 in g_simple_async_result_get_source_tag (simple=simple@entry=0xe8fdf0 [GSimpleAsyncResult]) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gsimpleasyncresult.c:495
#1  0x00007f62025f09d8 in _g_dbus_worker_do_read_cb (error=0x7f61f34ddaa0, result=0xe8fdf0, socket=0xee1130 [GSocket]) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gdbusprivate.c:222
        _g_boolean_var_ = <optimized out>
        simple = 0xe8fdf0 [GSimpleAsyncResult]
        worker = 0xef0710
        error = 0x0
        bytes_read = <optimized out>
#2  0x00007f62025f09d8 in _g_dbus_worker_do_read_cb (input_stream=<optimized out>, res=0xe8fdf0, user_data=0xef0710) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gdbusprivate.c:589
        worker = 0xef0710
        error = 0x0
        bytes_read = <optimized out>
#3  0x00007f6202583df7 in g_simple_async_result_complete (simple=0xe8fdf0 [GSimpleAsyncResult]) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gsimpleasyncresult.c:763
        current_source = 0xf8a090
        current_context = <optimized out>
        __FUNCTION__ = "g_simple_async_result_complete"
#4  0x00007f6202583e59 in complete_in_idle_cb (data=<optimized out>) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gsimpleasyncresult.c:775
        simple = <optimized out>
#5  0x00007f6201de3b4d in g_main_context_dispatch (context=0xed1100) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3122
        dispatch = 0x7f6201de0610 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0xe8fdf0
        callback = 0x7f6202583e50 <complete_in_idle_cb>
        cb_funcs = <optimized out>
        cb_data = 0xfffa00
        need_destroy = <optimized out>
        source = 0xf8a090
        current = 0xee8d90
        i = 0
#6  0x00007f6201de3b4d in g_main_context_dispatch (context=context@entry=0xed1100) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3737
#7  0x00007f6201de3f20 in g_main_context_iterate (context=0xed1100, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3808
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 2
        fds = 0xed0d70
#8  0x00007f6201de4242 in g_main_loop_run (loop=0xee6820) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:4002
        __FUNCTION__ = "g_main_loop_run"
#9  0x00007f62025eeaf6 in gdbus_shared_thread_func (user_data=0xed10d0) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gdbusprivate.c:274
        data = 0xed10d0
#10 0x00007f6201e0a955 in g_thread_proxy (data=0xe9a2d0) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gthread.c:764
        thread = 0xe9a2d0
#11 0x00007f6201b850a4 in start_thread (arg=0x7f61f34de700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7f61f34de700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140058670524160, -3998110244094618693, 0, 140059009171552, 140058915023104, 140058670524160, 3909192035573420987, 3911332960942019515}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#12 0x00007f62018ba04d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f620777ba00 (LWP 6933)):
#0  0x0000000000425a47 in feedlist_get_selected () at feedlist.c:217
#1  0x0000000000447649 in liferea_shell_destroy () at liferea_shell.c:1400
        node = <optimized out>
        item = <optimized out>
#2  0x000000000043141b in on_shutdown (user_data=<optimized out>) at main.c:294
        user_data = <optimized out>
#3  0x00007f6201de3b4d in g_main_context_dispatch (context=0xeabc80) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3122
        dispatch = 0x7f6201de0610 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x4313f0 <on_shutdown>
        cb_funcs = <optimized out>
        cb_data = 0xf68db0
        need_destroy = <optimized out>
        source = 0xf9c7d0
        current = 0xeab150
        i = 0
#4  0x00007f6201de3b4d in g_main_context_dispatch (context=context@entry=0xeabc80) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3737
#5  0x00007f6201de3f20 in g_main_context_iterate (context=context@entry=0xeabc80, block=block@entry=0, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3808
        max_priority = 200
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x10b0a70
#6  0x00007f6201de3fcc in g_main_context_iteration (context=0xeabc80, context@entry=0x0, may_block=may_block@entry=0) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./glib/gmain.c:3869
        retval = <optimized out>
#7  0x00007f62025b86e1 in g_application_run (application=0xef4230 [GtkApplication], argc=argc@entry=0, argv=argv@entry=0x0) at /build/glib2.0-NiYzoW/glib2.0-2.44.1/./gio/gapplication.c:2328
        arguments = 0x10a6470
        status = 1
        __FUNCTION__ = "g_application_run"
#8  0x000000000041b640 in main (argc=1, argv=0x7ffc2c9c4b48) at main.c:262
        app = 0xef4230 [GtkApplication]
        error = 0x0
        context = <optimized out>
        debug = <optimized out>
        debug_flags = 0
        dbus = 0xfe8520 [LifereaDBus]
        feedUri = 0x0
        status = <optimized out>
        entries = {{long_name = 0x45fa65 "mainwindow-state", short_name = 119 'w', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x67eea0 <initialStateOption>, description = 0x45fb00 "Start Liferea with its main window in STATE. STATE may be `shown', `iconified', or `hidden'", arg_description = 0x45fa76 "STATE"}, {long_name = 0x45a939 "version", short_name = 118 'v', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431100 <show_version>, description = 0x45fb60 "Show version information and exit", arg_description = 0x0}, {long_name = 0x45fa7c "add-feed", short_name = 97 'a', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x7ffc2c9c46b8, description = 0x45fa85 "Add a new subscription", arg_description = 0x46a385 "uri"}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        debug_entries = {{long_name = 0x45f99e "debug-all", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fc18 "Print debugging messages of all types", arg_description = 0x0}, {long_name = 0x45f9aa "debug-cache", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fc40 "Print debugging messages for the cache handling", arg_description = 0x0}, {long_name = 0x45f9b8 "debug-conf", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fc70 "Print debugging messages for the configuration handling", arg_description = 0x0}, {long_name = 0x45f9c5 "debug-db", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fca8 "Print debugging messages of the database handling", arg_description = 0x0}, {long_name = 0x45f9d0 "debug-gui", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fce0 "Print debugging messages of all GUI functions", arg_description = 0x0}, {long_name = 0x45f9dc "debug-html", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fd10 "Enables HTML rendering debugging. Each time Liferea renders HTML output it will also dump the generated HTML into ~/.cache/liferea/output.xhtml", arg_description = 0x0}, {long_name = 0x45f9e9 "debug-net", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fda0 "Print debugging messages of all network activity", arg_description = 0x0}, {long_name = 0x45f9f5 "debug-parsing", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fdd8 "Print debugging messages of all parsing functions", arg_description = 0x0}, {long_name = 0x45fa05 "debug-performance", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fe10 "Print debugging messages when a function takes too long to process", arg_description = 0x0}, {long_name = 0x45fa19 "debug-trace", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fe58 "Print debugging messages when entering/leaving functions", arg_description = 0x0}, {long_name = 0x45fa27 "debug-update", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fe98 "Print debugging messages of the feed update processing", arg_description = 0x0}, {long_name = 0x45fa36 "debug-vfolder", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45fed0 "Print debugging messages of the search folder matching", arg_description = 0x0}, {long_name = 0x45fa46 "debug-verbose", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x431220 <debug_entries_parse_callback>, description = 0x45ff08 "Print verbose debugging messages", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        __PRETTY_FUNCTION__ = "main"
```

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
