### ISSUE TITLE
Liferea crashes after startup

### ISSUE THREAD

**Issue by zaari** [lwindolf/liferea#281]
```[gauri ~]$ ulimit -c unlimited
[gauri ~]$ liferea --debug-all
CONF   : proxy auto detect is configured
CONF   : Manual proxy settings are now NULL:0 NULL:NULL
NET    : proxy set to http://(null):(null)@(null):0
DB     : Opening DB file /home/timo/.local/share/liferea/liferea.db...
DB     : executing SQL: PRAGMA journal_mode=WAL
DB     :  -> result: 0 (success)
DB     : executing SQL: PRAGMA page_size=32768
DB     :  -> result: 0 (success)
DB     : executing SQL: PRAGMA synchronous=NORMAL
DB     :  -> result: 0 (success)
DB     : current DB schema version: 10
DB     : No VACUUM as freelist count/page count ratio 1,13 <= 10
DB     : executing SQL: CREATE TABLE items (   item_id      INTEGER,   parent_item_id     INTEGER,   node_id        TEXT,   parent_node_id     TEXT,   title        TEXT,   read        INTEGER,   updated      INTEGER,   popup        INTEGER,   marked       INTEGER,   source       TEXT,   source_id       TEXT,   valid_guid      INTEGER,   description  TEXT,   date        INTEGER,   comment_feed_id  TEXT,   comment            INTEGER,   PRIMARY KEY (item_id));
DB     :  -> result: 1 (table items already exists)
DB     : executing SQL: CREATE INDEX items_idx ON items (source_id);
DB     :  -> result: 1 (index items_idx already exists)
DB     : executing SQL: CREATE INDEX items_idx2 ON items (comment_feed_id);
DB     :  -> result: 1 (index items_idx2 already exists)
DB     : executing SQL: CREATE INDEX items_idx3 ON items (node_id);
DB     :  -> result: 1 (index items_idx3 already exists)
DB     : executing SQL: CREATE INDEX items_idx4 ON items (item_id);
DB     :  -> result: 1 (index items_idx4 already exists)
DB     : executing SQL: CREATE INDEX items_idx5 ON items (parent_item_id);
DB     :  -> result: 1 (index items_idx5 already exists)
DB     : executing SQL: CREATE INDEX items_idx6 ON items (parent_node_id);
DB     :  -> result: 1 (index items_idx6 already exists)
DB     : executing SQL: CREATE TABLE metadata (   item_id       INTEGER,   nr              INTEGER,   key               TEXT,   value               TEXT,   PRIMARY KEY (item_id, nr));
DB     :  -> result: 1 (table metadata already exists)
DB     : executing SQL: CREATE INDEX metadata_idx ON metadata (item_id);
DB     :  -> result: 1 (index metadata_idx already exists)
DB     : executing SQL: CREATE TABLE subscription (   node_id            STRING,   source             STRING,   orig_source        STRING,   filter_cmd         STRING,   update_interval   INTEGER,   default_interval   INTEGER,   discontinued       INTEGER,   available          INTEGER,   PRIMARY KEY (node_id));
DB     :  -> result: 1 (table subscription already exists)
DB     : executing SQL: CREATE TABLE subscription_metadata (   node_id            STRING,   nr                 INTEGER,   key                TEXT,   value              TEXT,   PRIMARY KEY (node_id, nr));
DB     :  -> result: 1 (table subscription_metadata already exists)
DB     : executing SQL: CREATE INDEX subscription_metadata_idx ON subscription_metadata (node_id);
DB     :  -> result: 1 (index subscription_metadata_idx already exists)
DB     : executing SQL: CREATE TABLE node (   node_id       STRING,   parent_id     STRING,   title     STRING,   type      INTEGER,   expanded           INTEGER,   view_mode  INTEGER,   sort_column  INTEGER,   sort_reversed    INTEGER,   PRIMARY KEY (node_id));
DB     :  -> result: 1 (table node already exists)
DB     : executing SQL: CREATE TABLE search_folder_items (   node_id            STRING,   parent_node_id     STRING,   item_id      INTEGER,   PRIMARY KEY (node_id, item_id));
DB     :  -> result: 1 (table search_folder_items already exists)
DB     : executing SQL: DROP TRIGGER item_insert;
DB     :  -> result: 1 (no such trigger: item_insert)
DB     : executing SQL: DROP TRIGGER item_update;
DB     :  -> result: 1 (no such trigger: item_update)
DB     : executing SQL: DROP TRIGGER item_removal;
DB     :  -> result: 1 (no such trigger: item_removal)
DB     : executing SQL: DROP TRIGGER subscription_removal;
DB     :  -> result: 1 (no such trigger: subscription_removal)
DB     : Checking for items without a feed list node...

DB     : executing SQL: DELETE FROM items WHERE comment = 0 AND node_id NOT IN (SELECT node_id FROM node);

*\* (liferea:640): WARNING **: Unexpected status on SQL execution: 11 (database disk image is malformed)
DB     : Checking for comments without parent item...

DB     : executing SQL: BEGIN;    CREATE TEMP TABLE tmp_id ( id );   INSERT INTO tmp_id SELECT item_id FROM items WHERE comment = 1 AND parent_item_id NOT IN (SELECT item_id FROM items WHERE comment = 0);   DELETE FROM items WHERE item_id IN (SELECT id FROM tmp_id LIMIT 1000);   DROP TABLE tmp_id;END;

*\* (liferea:640): WARNING **: Unexpected status on SQL execution: 11 (database disk image is malformed)
DB     : Checking for search folder items without a feed list node...

DB     : executing SQL: DELETE FROM search_folder_items WHERE parent_node_id NOT IN (SELECT node_id FROM node);
DB     :  -> result: 0 (success)
DB     : Checking for search folder items without a search folder...

DB     : executing SQL: DELETE FROM search_folder_items WHERE node_id NOT IN (SELECT node_id FROM node);
DB     :  -> result: 0 (success)
DB     : Checking for search folder with comments...

DB     : executing SQL: DELETE FROM search_folder_items WHERE comment = 1;
DB     :  -> result: 1 (no such column: comment)
DB     : Checking for subscription metadata without node...

DB     : executing SQL: DELETE FROM subscription_metadata WHERE node_id NOT IN (SELECT node_id FROM node);
DB     :  -> result: 0 (success)
DB     : DB cleanup finished. Continuing startup.
DB     : executing SQL: CREATE TRIGGER item_removal DELETE ON items BEGIN    DELETE FROM metadata WHERE item_id = old.item_id;    DELETE FROM search_folder_items WHERE item_id = old.item_id; END;
DB     :  -> result: 0 (success)
DB     : executing SQL: CREATE TRIGGER subscription_removal DELETE ON subscription BEGIN    DELETE FROM node WHERE node_id = old.node_id;    DELETE FROM subscription_metadata WHERE node_id = old.node_id;    DELETE FROM search_folder_items WHERE parent_node_id = old.node_id; END;
DB     :  -> result: 0 (success)
**
ERROR:db.c:729:db_init: assertion failed: (sqlite3_get_autocommit (db))
Aborted (core dumped)

gauri ~]$ coredumpctl gdb 640
           PID: 640 (liferea)
           UID: 1000 (timo)
           GID: 9999 (perhe)
        Signal: 6 (ABRT)
     Timestamp: su 2015-10-25 17:20:37 EET (6min ago)
  Command Line: liferea --debug-all
    Executable: /usr/bin/liferea
 Control Group: /user.slice/user-1000.slice/user@1000.service/dbus.service
          Unit: user@1000.service
         Slice: user-1000.slice
     Owner UID: 1000 (timo)
       Boot ID: 4e0b64b307b4493ebb504163ab738d53
    Machine ID: 15cf66dde30c473388284fa6000dbb82
      Hostname: gauri
      Coredump: /var/lib/systemd/coredump/core.liferea.1000.4e0b64b307b4493ebb504163ab738d53.640.1445786437000000.lz4
       Message: Process 640 (liferea) of user 1000 dumped core.

GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/liferea...(no debugging symbols found)...done.
[New LWP 640]
[New LWP 644]
[New LWP 642]
[New LWP 643]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `liferea --debug-all'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb0c23b75f8 in raise () from /usr/lib/libc.so.6

[Current thread is 1 (Thread 0x7fb0c80ad9c0 (LWP 640))](gdb) bt
#0  0x00007fb0c23b75f8 in raise () from /usr/lib/libc.so.6
#1  0x00007fb0c23b8a7a in abort () from /usr/lib/libc.so.6
#2  0x00007fb0c29b48c5 in g_assertion_message () from /usr/lib/libglib-2.0.so.0
#3  0x00007fb0c29b495a in g_assertion_message_expr () from /usr/lib/libglib-2.0.so.0
#4  0x000000000041f7e2 in db_init ()
#5  0x000000000041b5c1 in main ()```

**Comment by zaari** [comment]
Liferea 1.10.16 on 64-bit Arch Linux

**Comment by lwindolf** [comment]
Can you move ~/.local/share/liferea/liferea.db to a temporary location and try if the error still appears?

**Comment by zaari** [comment]
That's the workaround, I have used many times, when Liferea refuses to start because of the core dump issue. It works, but unfortunately you lose the read status of the posts.

**Comment by lwindolf** [comment]
Do you still experience the issue?
