### ISSUE TITLE
Segmentation fault after updating Liferea from 1.8.8 to 1.10.9

### ISSUE THREAD

**Issue by vakuum** [lwindolf/liferea#30]
I updated Liferea from 1.8.8 to 1.10.9 and now I get a segmentation fault during start up:

```
$ liferea --version
Liferea 1.10.9

$ which liferea
/opt/liferea/bin/liferea

$ export XDG_DATA_DIRS=/opt/liferea/share:$XDG_DATA_DIRS

$ liferea --debug-trace
TRACE  : [0x923010] + db_init
TRACE  : [0x923010] - db_init
TRACE  : [0x923010] + liferea_dbus_new
TRACE  : [0x923010] - liferea_dbus_new
TRACE  : [0x923010] + liferea_shell_create
TRACE  : [0x923010]    + feed_list_view_init
TRACE  : [0x923010]    - feed_list_view_init
TRACE  : [0x923010]    + itemview_init
TRACE  : [0x923010]    - itemview_init
TRACE  : [0x923010]    + feedlist_init
TRACE  : [0x923010]       + node_source_setup_root
TRACE  : [0x923010]          + default_source_source_import
TRACE  : [0x923010]             + import_parse_outline
TRACE  : [0x923010]                + favicon_load_from_cache
...
TRACE  : [0x923010]             - import_parse_outline
TRACE  : [0x923010]          - default_source_source_import
TRACE  : [0x923010]       - node_source_setup_root
Segmentation fault (core dumped)
```

The backtrace from the core file:

```
$ gdb /opt/liferea/bin/liferea
...
(gdb) core-file core
...
(gdb) backtrace
#0  0x00007fe00f71a56a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe00fbfd789 in g_str_equal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x000000000041ddd7 in db_node_find (id=0x0, node=<optimized out>) at db.c:1590
#3  0x000000000042040d in db_node_update (node=0x0) at db.c:1567
#4  0x00000000024f9270 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb)
```

Start up works fine after adding a NULL pointer check to line 1590 in src/db.c:

```
    if (id != NULL && g_str_equal (node->id, (gchar *)id))
        return TRUE;
```

**Comment by lwindolf** [comment]
Sorry, should have worked on this sooner. I somehow overlooked the issue. I added a similar fix as you suggested. Thanks for the detailed debugging!
