### ISSUE TITLE
latest git master segfaults on startup

### ISSUE THREAD

**Issue by bitlord** [lwindolf/liferea#390]
I have been using "unofficial" webkit2 port for some time, so when I saw that it is merged, I compiled latest code from official repo (from today (9d444448143ac7f53a3a10cae8e1f252320938d9)), but I'm unable to run liferea it crashes on startup, also tried moving all config files known to me ~/.{cacahe,config,local}, here is the stack trace:

```
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x0000000000445532 in liferea_htmlview_new (forceInternalBrowsing=forceInternalBrowsing@entry=0) at liferea_htmlview.c:303
        htmlview = 0xa8e530
        __PRETTY_FUNCTION__ = "liferea_htmlview_new"
#2  0x00000000004444f9 in itemview_set_layout (newMode=NODE_VIEW_MODE_WIDE) at itemview.c:422
        renderWidget = <optimized out>
        ivp = 0xa8b190
        htmlWidgetName = <optimized out>
        ilWidgetName = <optimized out>
        encViewVBoxName = <optimized out>
        __PRETTY_FUNCTION__ = "itemview_set_layout"
        __func__ = "itemview_set_layout"
#3  0x00000000004446cb in itemview_create (window=<optimized out>) at itemview.c:508
        zoom = 172
#4  0x0000000000448343 in liferea_shell_create (app=app@entry=0x6fb2b0, overrideWindowState=0x0) at liferea_shell.c:1340
        ui_manager = <optimized out>
        accel_group = <optimized out>
        error = 0x0
        toggle = 0
        id = 0x7ffff7de2caf <_dl_lookup_symbol_x+335> "H\203\304\060\203", <incomplete sequence \370>
        __PRETTY_FUNCTION__ = "liferea_shell_create"
#5  0x0000000000430ac7 in on_app_activate (app=0x6fb2b0, user_data=0x0) at main.c:86
        list = <optimized out>
        feedUri = 0x0
#6  0x00007fffee5a0f45 in g_closure_invoke (closure=0x74aa20, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7fffffffd660, 
    invocation_hint=invocation_hint@entry=0x7fffffffd5e0) at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gobject/gclosure.c:804
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0x74aa00
        __func__ = "g_closure_invoke"
#7  0x00007fffee5b2f61 in signal_emit_unlocked_R (node=node@entry=0x729d80, detail=detail@entry=0, instance=instance@entry=0x6fb2b0, 
    emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd660)
    at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gobject/gsignal.c:3629
        tmp = <optimized out>
        handler = 0x879740
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x6fb2b0, ihint = {signal_id = 214, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
        handler_list = 0x879740
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {
              v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 214
        max_sequential_handler_number = 52
        return_value_altered = 0
#8  0x00007fffee5bbcfc in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd810)
    at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gobject/gsignal.c:3385
        instance_and_params = 0x7fffffffd660
        signal_return_type = <optimized out>
---Type <return> to continue, or q <return> to quit---
        param_values = 0x7fffffffd678
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#9  0x00007fffee5bc02f in g_signal_emit (instance=instance@entry=0x6fb2b0, signal_id=<optimized out>, detail=detail@entry=0)
    at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gobject/gsignal.c:3441
        var_args = <error reading variable var_args (Attempt to dereference a generic pointer.)>
#10 0x00007fffeeac609b in g_application_activate (application=application@entry=0x6fb2b0)
    at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gio/gapplication.c:2148
        __func__ = "g_application_activate"
#11 0x00007fffeeac6866 in g_application_real_local_command_line (application=0x6fb2b0, arguments=0x7fffffffda18, exit_status=0x7fffffffda14)
    at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gio/gapplication.c:1045
        error = 0x0
        n_args = 0
#12 0x00007fffeeac6a52 in g_application_run (application=0x6fb2b0, argc=argc@entry=0, argv=argv@entry=0x0)
    at /var/tmp/portage/dev-libs/glib-2.48.2/work/glib-2.48.2/gio/gapplication.c:2350
        arguments = 0x792a60
        status = -1
        context = 0x6ac890
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#13 0x000000000041b10c in main (argc=1, argv=0x7fffffffdf18) at main.c:271
        app = 0x6fb2b0
        error = 0x0
        context = <optimized out>
        debug = <optimized out>
        debug_flags = 0
        dbus = 0x7da800
        feedUri = 0x0
        status = <optimized out>
        entries = {{long_name = 0x45ff45 "mainwindow-state", short_name = 119 'w', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x67f8c8 <initialStateOption>, 
            description = 0x45fff0 "Start Liferea with its main window in STATE. STATE may be `shown' or `hidden'", arg_description = 0x45ff56 "STATE"}, {
            long_name = 0x45b25a "version", short_name = 118 'v', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x4309d0 <show_version>, 
            description = 0x460040 "Show version information and exit", arg_description = 0x0}, {long_name = 0x45ff5c "add-feed", short_name = 97 'a', flags = 0, 
            arg = G_OPTION_ARG_STRING, arg_data = 0x7fffffffda98, description = 0x45ff65 "Add a new subscription", arg_description = 0x46b636 "uri"}, {
            long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        debug_entries = {{long_name = 0x45fe7e "debug-all", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, 
            arg_data = 0x430af0 <debug_entries_parse_callback>, description = 0x4600f8 "Print debugging messages of all types", arg_description = 0x0}, {
            long_name = 0x45fe8a "debug-cache", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x460120 "Print debugging messages for the cache handling", arg_description = 0x0}, {long_name = 0x45fe98 "debug-conf", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x460150 "Print debugging messages for the configuration handling", arg_description = 0x0}, {long_name = 0x45fea5 "debug-db", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x460188 "Print debugging messages of the database handling", arg_description = 0x0}, {long_name = 0x45feb0 "debug-gui", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x4601c0 "Print debugging messages of all GUI functions", arg_description = 0x0}, {long_name = 0x45febc "debug-html", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x4601f0 "Enables HTML rendering debugging. Each time Liferea renders HTML output it will also dump the generated HTML into ~/.cache/liferea/output.xhtml", arg_description = 0x0}, {long_name = 0x45fec9 "debug-net", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, 
            arg_data = 0x430af0 <debug_entries_parse_callback>, description = 0x460280 "Print debugging messages of all network activity", arg_description = 0x0}, {
---Type <return> to continue, or q <return> to quit---
            long_name = 0x45fed5 "debug-parsing", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x4602b8 "Print debugging messages of all parsing functions", arg_description = 0x0}, {long_name = 0x45fee5 "debug-performance", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x4602f0 "Print debugging messages when a function takes too long to process", arg_description = 0x0}, {
            long_name = 0x45fef9 "debug-trace", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x460338 "Print debugging messages when entering/leaving functions", arg_description = 0x0}, {long_name = 0x45ff07 "debug-update", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x460378 "Print debugging messages of the feed update processing", arg_description = 0x0}, {long_name = 0x45ff16 "debug-vfolder", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x4603b0 "Print debugging messages of the search folder matching", arg_description = 0x0}, {long_name = 0x45ff26 "debug-verbose", 
            short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x430af0 <debug_entries_parse_callback>, 
            description = 0x4603e8 "Print verbose debugging messages", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, 
            arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        __PRETTY_FUNCTION__ = "main"
(gdb)
``` 

P.S. thank you for making this awesome software! (like it being webkit2) ;-)

**Comment by Leiaz** [comment]
Should also be fixed by #391 I think ?

**Comment by bitlord** [comment]
Thank you @Leiaz that commit fixes the issues on startup with fresh or old config! :-)

**Comment by lwindolf** [comment]
#391 is merged.
