### ISSUE TITLE
1.12-RC1: enabling/disabling Tray Icon plugin regularly raises Gdk-ERROR

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#409]
With the 1.12-RC1 release package I created in Debian, I am experiencing an often reproducible crash when I enable and disable the Tray Icon plugin in (quick) succession. Looks a little bit like a race condition.

Until now, if I run liferea with GDK_SYNCHRONIZE=true as suggested by the error, I haven't been able to reproduce yet.

```
paul@testavoira ~/liferea $ gdb liferea
GNU gdb (Debian 7.11.1-2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from liferea...Reading symbols from /usr/lib/debug/.build-id/d8/3cc10d57a93b5f05c5c76a5a995b488324beb7.debug...done.
done.
(gdb) run
Starting program: /usr/bin/liferea 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe105e700 (LWP 5611)]
[New Thread 0x7fffe0258700 (LWP 5613)]
[New Thread 0x7fffdfa57700 (LWP 5614)]
[New Thread 0x7fffdf256700 (LWP 5615)]
[New Thread 0x7fffde72e700 (LWP 5616)]

(liferea:5607): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(liferea:5607): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(liferea:5607): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
[New Thread 0x7fffdd7ff700 (LWP 5617)]
[New Thread 0x7fffdcffe700 (LWP 5618)]
[New Thread 0x7fff87ffd700 (LWP 5619)]
[New Thread 0x7fff877fc700 (LWP 5622)]
[New Thread 0x7fff86df5700 (LWP 5635)]
[Thread 0x7fffde72e700 (LWP 5616) exited]
[New Thread 0x7fffde72e700 (LWP 5637)]
[New Thread 0x7fff85599700 (LWP 5638)]

(liferea:5607): Gtk-WARNING **: Allocating size to GtkWindow 0x5555558fe260 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[New Thread 0x7fff6ffff700 (LWP 5648)]
[New Thread 0x7fff6f7fe700 (LWP 5649)]
[New Thread 0x7fff6effd700 (LWP 5650)]
[New Thread 0x7fff6e7fc700 (LWP 5651)]
[Thread 0x7fff6e7fc700 (LWP 5651) exited]
[Thread 0x7fff6ffff700 (LWP 5648) exited]
[Thread 0x7fff6f7fe700 (LWP 5649) exited]
[Thread 0x7fff6effd700 (LWP 5650) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(liferea:5607): Gdk-ERROR **: The program 'liferea' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 22717 error_code 3 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Thread 1 "liferea" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff2995241 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff2995241 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff2997961 in g_log_writer_default () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff2995ddc in g_log_structured_array () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff29960d9 in g_log_structured () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff3b5840e in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff3b655e3 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007fffea8a446d in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fffea8a13a7 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007fffea8a1465 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007fffea8a1e15 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007fffea8936c7 in XPending () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007ffff3b5fb5e in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007ffff298eed9 in g_main_context_prepare () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff298f8fb in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff298faec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff317e70d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x0000555555571236 in main (argc=<optimized out>, argv=<optimized out>) at main.c:271
(gdb) quit
```

**Comment by lwindolf** [comment]
I can reproduce this. Some error checking is needed.
