### ISSUE TITLE
random crash: SIGABRT: assertion failed: (sqlite3_get_autocommit (db))

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#424]
This report is taken straight from the Debian bug 841255¹. Please close if it isn't actionable. Does this fall under the "Often people confuses assertions with crashes. Assertions do halt the program because of a totally unexpected situation. Creating a backtrace in this situation will only point to the assertion line, which doesn't help much. In case of an assertion simply post a bug report with the assertion message." note in the "How can I help" section of README.md?

¹ https://bugs.debian.org/841255

I got a random crash (SIGABRT) in liferea. If the below gdb backtrace
isn't useful, please close this bug.

```
$ gdb -batch -n -ex 'set pagination off' -ex bt -ex 'thread apply all bt full' --core /var/crash/1000/31138-1000-1000-6-1476805337-chianamo--usr-bin-liferea.core /usr/bin/liferea
[New LWP 31138]
[New LWP 31155]
[New LWP 31150]
[New LWP 31154]
[New LWP 31156]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `liferea'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb261403400 (LWP 31138))]
#0  0x00007fb25b8affdf in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007fb25b8b140a in __GI_abort () at abort.c:89
#2  0x00007fb25bea94f5 in g_assertion_message (domain=domain@entry=0x0, file=file@entry=0x55b36b89ebb2 "db.c", line=line@entry=729, func=func@entry=0x55b36b89f600 <__func__.60456> "db_init", message=message@entry=0x55b36c6a2920 "assertion failed: (sqlite3_get_autocommit (db))") at ././glib/gtestutils.c:2429
#3  0x00007fb25bea958a in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x55b36b89ebb2 "db.c", line=line@entry=729, func=func@entry=0x55b36b89f600 <__func__.60456> "db_init", expr=expr@entry=0x55b36b89f032 "sqlite3_get_autocommit (db)") at ././glib/gtestutils.c:2452
#4  0x000055b36b861491 in db_init () at db.c:729
#5  0x000055b36b85d185 in main (argc=<optimized out>, argv=<optimized out>) at main.c:240

Thread 5 (Thread 0x7fb243fff700 (LWP 31156)):
#0  0x00007fb25b95c50d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fb25be829d6 in g_main_context_iterate (priority=<optimized out>, n_fds=2, fds=0x7fb2380010c0, timeout=<optimized out>, context=0x7fb244011dc0) at ././glib/gmain.c:4228
        poll_func = 0x7fb25be92820 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7fb2380010c0
#2  0x00007fb25be829d6 in g_main_context_iterate (context=0x7fb244011dc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3924
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7fb2380010c0
#3  0x00007fb25be82d62 in g_main_loop_run (loop=0x7fb244011d50) at ././glib/gmain.c:4125
        __func__ = "g_main_loop_run"
#4  0x00007fb25c69e4e6 in gdbus_shared_thread_func (user_data=0x7fb244011d90) at ././gio/gdbusprivate.c:247
        data = 0x7fb244011d90
#5  0x00007fb25beaa325 in g_thread_proxy (data=0x55b36c560720) at ././glib/gthread.c:784
        thread = 0x55b36c560720
#6  0x00007fb25bc22464 in start_thread (arg=0x7fb243fff700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb243fff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140403621754624, 1729578137496448398, 0, 140403711854591, 0, 140404113477696, -1773233147832308338, -1773286154421146226}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007fb25b96597f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 4 (Thread 0x7fb2495ed700 (LWP 31154)):
#0  0x00007fb25b95c50d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fb25be829d6 in g_main_context_iterate (priority=<optimized out>, n_fds=1, fds=0x7fb2440010e0, timeout=<optimized out>, context=0x55b36c565be0) at ././glib/gmain.c:4228
        poll_func = 0x7fb25be92820 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7fb2440010e0
#2  0x00007fb25be829d6 in g_main_context_iterate (context=context@entry=0x55b36c565be0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3924
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7fb2440010e0
#3  0x00007fb25be82aec in g_main_context_iteration (context=context@entry=0x55b36c565be0, may_block=may_block@entry=1) at ././glib/gmain.c:3990
        retval = <optimized out>
#4  0x00007fb2495f546d in dconf_gdbus_worker_thread (user_data=0x55b36c565be0) at dconf-gdbus-thread.c:82
        context = 0x55b36c565be0
#5  0x00007fb25beaa325 in g_thread_proxy (data=0x55b36c560140) at ././glib/gthread.c:784
        thread = 0x55b36c560140
#6  0x00007fb25bc22464 in start_thread (arg=0x7fb2495ed700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb2495ed700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140403711858432, 1729578137496448398, 0, 140735576066847, 0, 140404113477696, -1773256504938205810, -1773286154421146226}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007fb25b96597f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 3 (Thread 0x7fb24a54d700 (LWP 31150)):
#0  0x00007fb25bc2818f in pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fb253058fcc in std::condition_variable::wait(std::unique_lock<std::mutex>&) (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc-6-vjs56i/gcc-6-6.2.0/build/x86_64-linux-gnu/libstdc++-v3/include/x86_64-linux-gnu/bits/gthr-default.h:864
        __e = <optimized out>
#2  0x00007fb253058fcc in std::condition_variable::wait(std::unique_lock<std::mutex>&) (this=<optimized out>, __lock=...) at ../../../../../src/libstdc++-v3/src/c++11/condition_variable.cc:53
        __e = <optimized out>
#3  0x00007fb25815fbb6 in bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() () at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18
#4  0x00007fb25815fce9 in  () at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18
#5  0x00007fb25305e90f in std::execute_native_thread_routine(void*) (__p=0x55b36c539ba0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:83
        __t = std::unique_ptr<std::thread::_State> containing 0x55b36c539ba0
#6  0x00007fb25bc22464 in start_thread (arg=0x7fb24a54d700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb24a54d700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140403727980288, 1729578137496448398, 0, 140735576068863, 0, 140404113477696, -1773249959408046706, -1773286154421146226}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007fb25b96597f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 2 (Thread 0x7fb248dec700 (LWP 31155)):
#0  0x00007fb25b95c50d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fb25be829d6 in g_main_context_iterate (priority=<optimized out>, n_fds=1, fds=0x7fb23c0008c0, timeout=<optimized out>, context=0x7fb244011580) at ././glib/gmain.c:4228
        poll_func = 0x7fb25be92820 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7fb23c0008c0
#2  0x00007fb25be829d6 in g_main_context_iterate (context=context@entry=0x7fb244011580, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3924
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7fb23c0008c0
#3  0x00007fb25be82aec in g_main_context_iteration (context=0x7fb244011580, may_block=may_block@entry=1) at ././glib/gmain.c:3990
        retval = <optimized out>
#4  0x00007fb25be82b31 in glib_worker_main (data=<optimized out>) at ././glib/gmain.c:5783
#5  0x00007fb25beaa325 in g_thread_proxy (data=0x55b36c5606d0) at ././glib/gthread.c:784
        thread = 0x55b36c5606d0
#6  0x00007fb25bc22464 in start_thread (arg=0x7fb248dec700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb248dec700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140403703465728, 1729578137496448398, 0, 140403711854239, 0, 140404113477696, -1773253206940193394, -1773286154421146226}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007fb25b96597f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 1 (Thread 0x7fb261403400 (LWP 31138)):
#0  0x00007fb25b8affdf in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
        set = {__val = {0, 140404113262464, 140735576067616, 5925388399, 140404113261608, 140735576067600, 140404022619623, 252833149, 4294967295, 18446744073692774400, 140404016561624, 140404113248256, 32, 0, 2064, 94229107846464}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007fb25b8b140a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x643a3932373a632e, sa_sigaction = 0x643a3932373a632e}, sa_mask = {__val = {2322296554035699554, 71, 140735576068112, 140735576067984, 13850509446027508224, 94229107360976, 0, 140404074741760, 94229091707826, 0, 0, 4294967295, 0, 140404020304672, 94229107846464, 0}}, sa_flags = 1544860512, sa_restorer = 0x55b36c802d40}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fb25bea94f5 in g_assertion_message (domain=domain@entry=0x0, file=file@entry=0x55b36b89ebb2 "db.c", line=line@entry=729, func=func@entry=0x55b36b89f600 <__func__.60456> "db_init", message=message@entry=0x55b36c6a2920 "assertion failed: (sqlite3_get_autocommit (db))") at ././glib/gtestutils.c:2429
        lstr = "729\000\377\177\000\000\000z\251@\365\344\066\300\r\000\000\000\000\000\000\000\062\360\211k\263U\000"
        s = 0x55b36c802d40 ""
#3  0x00007fb25bea958a in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x55b36b89ebb2 "db.c", line=line@entry=729, func=func@entry=0x55b36b89f600 <__func__.60456> "db_init", expr=expr@entry=0x55b36b89f032 "sqlite3_get_autocommit (db)") at ././glib/gtestutils.c:2452
        s = 0x55b36c6a2920 "assertion failed: (sqlite3_get_autocommit (db))"
#4  0x000055b36b861491 in db_init () at db.c:729
        res = <optimized out>
        __PRETTY_FUNCTION__ = "db_init"
        __func__ = "db_init"
#5  0x000055b36b85d185 in main (argc=<optimized out>, argv=<optimized out>) at main.c:240
        app = 0x55b36c5862c0 [GtkApplication]
        error = 0x0
        context = <optimized out>
        debug = <optimized out>
        debug_flags = 0
        dbus = 0x0
        feedUri = 0x0
        status = <optimized out>
        entries = {{long_name = 0x55b36b8a4d05 "mainwindow-state", short_name = 119 'w', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x55b36bac52b0 <initialStateOption>, description = 0x55b36b8a4da0 "Start Liferea with its main window in STATE. STATE may be `shown' or `hidden'", arg_description = 0x55b36b8a4d16 "STATE"}, {long_name = 0x55b36b8a006a "version", short_name = 118 'v', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b873f30 <show_version>, description = 0x55b36b8a4df0 "Show version information and exit", arg_description = 0x0}, {long_name = 0x55b36b8a4d1c "add-feed", short_name = 97 'a', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x7fff8e04d118, description = 0x55b36b8a4d25 "Add a new subscription", arg_description = 0x55b36b8af528 "uri"}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        debug_entries = {{long_name = 0x55b36b8a4c3e "debug-all", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a4ea8 "Print debugging messages of all types", arg_description = 0x0}, {long_name = 0x55b36b8a4c4a "debug-cache", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a4ed0 "Print debugging messages for the cache handling", arg_description = 0x0}, {long_name = 0x55b36b8a4c58 "debug-conf", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a4f00 "Print debugging messages for the configuration handling", arg_description = 0x0}, {long_name = 0x55b36b8a4c65 "debug-db", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a4f38 "Print debugging messages of the database handling", arg_description = 0x0}, {long_name = 0x55b36b8a4c70 "debug-gui", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a4f70 "Print debugging messages of all GUI functions", arg_description = 0x0}, {long_name = 0x55b36b8a4c7c "debug-html", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a4fa0 "Enables HTML rendering debugging. Each time Liferea renders HTML output it will also dump the generated HTML into ~/.cache/liferea/output.xhtml", arg_description = 0x0}, {long_name = 0x55b36b8a4c89 "debug-net", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a5030 "Print debugging messages of all network activity", arg_description = 0x0}, {long_name = 0x55b36b8a4c95 "debug-parsing", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a5068 "Print debugging messages of all parsing functions", arg_description = 0x0}, {long_name = 0x55b36b8a4ca5 "debug-performance", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a50a0 "Print debugging messages when a function takes too long to process", arg_description = 0x0}, {long_name = 0x55b36b8a4cb9 "debug-trace", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a50e8 "Print debugging messages when entering/leaving functions", arg_description = 0x0}, {long_name = 0x55b36b8a4cc7 "debug-update", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a5128 "Print debugging messages of the feed update processing", arg_description = 0x0}, {long_name = 0x55b36b8a4cd6 "debug-vfolder", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a5160 "Print debugging messages of the search folder matching", arg_description = 0x0}, {long_name = 0x55b36b8a4ce6 "debug-verbose", short_name = 0 '\000', flags = 8, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55b36b874060 <debug_entries_parse_callback>, description = 0x55b36b8a5198 "Print verbose debugging messages", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        __PRETTY_FUNCTION__ = "main"
```

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
