### ISSUE TITLE
Failed to open file '/usr/share/liferea/search_dialog.ui'

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#473]
I think this problem was reported and fixed already.

Liferea 1.12-rc2

Steps to reproduce:
* Search
* Search All Feeds...
* Advanced...

```
$ liferea
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(liferea:4581): Gtk-ERROR **: failed to add UI: Failed to open file '/usr/share/liferea/search_dialog.ui': No such file or directory
Trace/breakpoint trap
```

**Comment by genodeftest** [comment]
Same issue here.

Shortened backtrace:
```
#0  0x00007ffff0949a21 in _g_log_abort (breakpoint=breakpoint@entry=1) at gmessages.c:487
#1  0x00007ffff094c161 in g_log_writer_default (log_level=6, 
    log_level@entry=G_LOG_LEVEL_ERROR, fields=fields@entry=0x7fffffffbaa0, n_fields=n_fields@entry=6, user_data=user_data@entry=0x0) at gmessages.c:2382
#2  0x00007ffff094a5bc in g_log_structured_array (log_level=G_LOG_LEVEL_ERROR, fields=0x7fffffffbaa0, n_fields=6) at gmessages.c:1770
#3  0x00007ffff094a8b9 in g_log_structured (log_domain=log_domain@entry=0x7ffff2cd0518 "Gtk", log_level=log_level@entry=G_LOG_LEVEL_ERROR) at gmessages.c:1597
#4  0x00007ffff2a2ba03 in gtk_builder_new_from_file (filename=filename@entry=0x1c6b0f0 "/usr/local/share/liferea/search_dialog.ui") at gtkbuilder.c:2583
#5  0x0000000000444439 in liferea_dialog_new (name=name@entry=0x468daf "search_dialog")
    at liferea_dialog.c:108
#6  0x0000000000449e7c in search_dialog_open (query=query@entry=0x7ffff2d49a4e "")
    at search_dialog.c:166
#7  0x000000000044a002 in search_dialog_open (query=0x7ffff2d49a4e "") at search_dialog.c:162
#8  0x000000000044a002 in on_simple_search_dialog_response (dialog=<optimized out>, responseId=2, user_data=0x1c6c8a0) at search_dialog.c:261
#9  0x00007ffff0c1e91e in g_cclosure_marshal_VOID__ENUMv (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x1828460) at gmarshal.c:1496
#10 0x00007ffff0c1c614 in _g_closure_invoke_va (closure=closure@entry=0x1c93680, return_value=return_value@entry=0x0, instance=instance@entry=0x1c61bf0, args=args@entry=0x7fffffffc460, n_params=<optimized out>, param_types=0x1828460) at gclosure.c:867
#11 0x00007ffff0c36dd9 in g_signal_emit_valist (instance=0x1c61bf0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffc460) at gsignal.c:3300
#12 0x00007ffff0c3743f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3447
#13 0x00007ffff0c1c614 in _g_closure_invoke_va (closure=closure@entry=0x1c82640, return_value=return_value@entry=0x0, instance=instance@entry=0x13236c0, args=args@entry=0x7fffffffc760, n_params=<optimized out>, param_types=0x0) at gclosure.c:867
#14 0x00007ffff0c36dd9 in g_signal_emit_valist (instance=0x13236c0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffc760) at gsignal.c:3300
#15 0x00007ffff0c3743f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3447
#16 0x00007ffff2a3178d in gtk_button_do_release (button=0x13236c0 [GtkButton], emit_clicked=<optimized out>) at gtkbutton.c:1843
#17 0x00007ffff2a317f5 in gtk_real_button_released (button=0x13236c0 [GtkButton]) at gtkbutton.c:1961
#18 0x00007ffff0c1c614 in _g_closure_invoke_va (closure=closure@entry=0x78e2d0, return_value=return_value@entry=0x0, instance=instance@entry=0x13236c0, args=args@entry=0x7fffffffcac0, n_params=<optimized out>, param_types=0x0) at gclosure.c:867
#19 0x00007ffff0c36dd9 in g_signal_emit_valist (instance=0x13236c0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffcac0) at gsignal.c:3300
#20 0x00007ffff0c3743f in g_signal_emit (instance=instance@entry=0x13236c0, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
#21 0x00007ffff2a2fbe0 in multipress_released_cb (gesture=0x12fa4d0 [GtkGestureMultiPress], n_press=<optimized out>, x=<optimized out>, y=<optimized out>, widget=0x13236c0 [GtkButton]) at gtkbutton.c:666
#22 0x00007fffe6477c58 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#23 0x00007fffe64776ba in ffi_call (cif=cif@entry=0x7fffffffce20, fn=fn@entry=0x7ffff2a2fbc0 <multipress_released_cb>, rvalue=<optimized out>, avalue=avalue@entry=0x7fffffffccf0) at ../src/x86/ffi64.c:525
#24 0x00007ffff0c1d0fa in g_cclosure_marshal_generic_va (closure=0x1c7f500, return_value=0x0, instance=<optimized out>, args_list=<optimized out>, marshal_data=<optimized out>, n_params=3, param_types=0x802020) at gclosure.c:1604
```
