### ISSUE TITLE
Segmentation fault when switching from a feed in "combined view"

### ISSUE THREAD

**Issue by jonmstone** [lwindolf/liferea#522]
I'm running 1.12-rc3 on FreeBSD 11.0-RELEASE-p10.  If I select a feed using the "Combined View" view type, and then select a different feed, Liferea core dumps with "Memory fault(coredump)".  These feeds and view configurations worked reliably on Liferea 1.10.18.

I've recompiled with "-O0 -g" and captured a core dump.  The back trace is:
```
(gdb) bt
#0  item_list_view_update_item (ilv=0x816113680, item=0x0)
    at item_list_view.c:473
#1  0x000000000046ef62 in item_list_view_update_all_items (ilv=0x816113680)
    at item_list_view.c:546
#2  0x000000000045c873 in itemview_update_all_items () at itemview.c:287
#3  0x000000000042cb25 in feedlist_mark_all_read (node=0x8169b4100)
    at feedlist.c:355
#4  0x0000000000432fb1 in itemlist_unload (markRead=1) at itemlist.c:350
#5  0x000000000042d5b6 in feedlist_selection_changed (node=0x8169b4000)
    at feedlist.c:590
#6  0x000000000045a3d7 in feed_list_view_selection_changed_cb (
    selection=0x8156ac5c0, data=0x815fd03e0) at feed_list_view.c:74
#7  0x0000000807bc4b49 in g_closure_invoke ()
   from /usr/local/lib/libgobject-2.0.so.0
#8  0x0000000807bd9c4d in g_signal_emit_valist ()
   from /usr/local/lib/libgobject-2.0.so.0
#9  0x0000000807bda4fc in g_signal_emit ()
   from /usr/local/lib/libgobject-2.0.so.0
#10 0x00000008059d9d82 in gtk_tree_view_set_model ()
   from /usr/local/lib/libgtk-3.so.0
#11 0x00000008059ed2a6 in gtk_tree_view_get_tooltip_column ()
   from /usr/local/lib/libgtk-3.so.0
#12 0x000000080fd1074c in ffi_call_unix64 () from /usr/local/lib/libffi.so.6
---Type <return> to continue, or q <return> to quit---
#13 0x000000080fd0fdad in ffi_call () from /usr/local/lib/libffi.so.6
#14 0x0000000807bc5ff9 in g_cclosure_marshal_generic_va ()
   from /usr/local/lib/libgobject-2.0.so.0
#15 0x0000000807bc4b49 in g_closure_invoke ()
   from /usr/local/lib/libgobject-2.0.so.0
#16 0x0000000807bd9c4d in g_signal_emit_valist ()
   from /usr/local/lib/libgobject-2.0.so.0
#17 0x0000000807bda4fc in g_signal_emit ()
   from /usr/local/lib/libgobject-2.0.so.0
#18 0x0000000805858228 in gtk_gesture_multi_press_get_area ()
   from /usr/local/lib/libgtk-3.so.0
#19 0x0000000807bc7bb1 in g_cclosure_marshal_VOID__BOXEDv ()
   from /usr/local/lib/libgobject-2.0.so.0
#20 0x0000000807bc4b49 in g_closure_invoke ()
   from /usr/local/lib/libgobject-2.0.so.0
#21 0x0000000807bd9c4d in g_signal_emit_valist ()
   from /usr/local/lib/libgobject-2.0.so.0
#22 0x0000000807bda4fc in g_signal_emit ()
   from /usr/local/lib/libgobject-2.0.so.0
#23 0x0000000805854ed6 in gtk_gesture_set_sequence_state ()
   from /usr/local/lib/libgtk-3.so.0
#24 0x000000080585669b in _gtk_gesture_get_pointer_emulating_sequence ()
   from /usr/local/lib/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#25 0x0000000805859cb1 in gtk_gesture_single_get_current_sequence ()
   from /usr/local/lib/libgtk-3.so.0
#26 0x0000000805824a3b in gtk_event_controller_handle_event ()
   from /usr/local/lib/libgtk-3.so.0
#27 0x0000000805a009fc in _gtk_widget_captured_event ()
   from /usr/local/lib/libgtk-3.so.0
#28 0x00000008058a5b9f in _gtk_marshal_BOOLEAN__BOXED ()
   from /usr/local/lib/libgtk-3.so.0
#29 0x0000000807bc48e1 in g_closure_invoke ()
   from /usr/local/lib/libgobject-2.0.so.0
#30 0x0000000807bd9279 in g_signal_emitv ()
   from /usr/local/lib/libgobject-2.0.so.0
#31 0x0000000807bd9f51 in g_signal_emit_valist ()
   from /usr/local/lib/libgobject-2.0.so.0
#32 0x0000000807bda4fc in g_signal_emit ()
   from /usr/local/lib/libgobject-2.0.so.0
#33 0x0000000805a00738 in gtk_widget_event () from /usr/local/lib/libgtk-3.so.0
#34 0x00000008058a47b0 in gtk_get_current_event_device ()
   from /usr/local/lib/libgtk-3.so.0
#35 0x00000008058a3e47 in gtk_main_do_event ()
   from /usr/local/lib/libgtk-3.so.0
#36 0x0000000805f6e7b1 in _gdk_event_emit () from /usr/local/lib/libgdk-3.so.0
#37 0x0000000805fa4407 in _gdk_x11_display_queue_events ()
---Type <return> to continue, or q <return> to quit---
   from /usr/local/lib/libgdk-3.so.0
#38 0x0000000807e4c445 in g_main_context_dispatch ()
   from /usr/local/lib/libglib-2.0.so.0
#39 0x0000000807e4c774 in g_main_context_pending ()
   from /usr/local/lib/libglib-2.0.so.0
#40 0x0000000807e4c804 in g_main_context_iteration ()
   from /usr/local/lib/libglib-2.0.so.0
#41 0x00000008076a2a0d in g_application_run ()
   from /usr/local/lib/libgio-2.0.so.0
#42 0x000000000043fe0b in main (argc=1, argv=0x7fffffffe940) at main.c:82
Current language:  auto; currently minimal
```

```
(gdb) up
#1  0x000000000046ef62 in item_list_view_update_all_items (ilv=0x816113680)
    at item_list_view.c:546
546                     item_list_view_update_item (ilv, item);
(gdb) list
541             model = gtk_tree_view_get_model (ilv->priv->treeview);
542             gtk_tree_model_get_iter_first (model, &iter);
543             while (valid) {
544                     gtk_tree_model_get (model, &iter, IS_NR, &id, -1);
545                     itemPtr item = item_load (id);
546                     item_list_view_update_item (ilv, item);
547                     item_unload (item);
548                     valid = gtk_tree_model_iter_next (model, &iter);
549             }
550     }
(gdb) print valid
$5 = 32767
(gdb) print id
$6 = 0
(gdb) print item
$1 = 0x0
(gdb) print ilv
$7 = (ItemListView *) 0x816113680
```
Looking at item_list_view_update_all_items(), it looks like `valid` is uninitialized on the first pass through the while() loop.

If I make this change to item_list_view.c:
```
--- src/ui/item_list_view.c.orig        2017-06-27 22:33:08.143515000 +0100
+++ src/ui/item_list_view.c     2017-06-27 22:33:25.233410000 +0100
@@ -539,7 +539,7 @@
        GtkTreeModel    *model;
 
        model = gtk_tree_view_get_model (ilv->priv->treeview);
-        gtk_tree_model_get_iter_first (model, &iter);
+        valid = gtk_tree_model_get_iter_first (model, &iter);
        while (valid) {
                gtk_tree_model_get (model, &iter, IS_NR, &id, -1);
                 itemPtr        item = item_load (id);
```
and recompile, then this appears to prevent the crash for me.

**Comment by lwindolf** [comment]
Thanks for reporting and debugging this!!!
