### ISSUE TITLE
Plugin manager won't open when there is no internet connectivity or a proxy is set

### ISSUE THREAD

**Issue by bbhtt** [lwindolf/liferea#978]
1. Set a proxy in GNOME Control center:

```
Manual
SOCKS5 
localhost:9050
Ignore hosts: 127.0.0.0/8, ::1
```
2. For liferea >Auto detect proxy
3. Open Liferea and try to open Tools>Plugins
4. Plugin manager dialogue won't open.
5. Error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/liferea/plugins/plugin-installer.py", line 62, in _run
    self._browser = PluginBrowser()
  File "/app/lib/liferea/plugins/plugin-installer.py", line 89, in __init__
    self._plugin_list = self.fetch_list()
  File "/app/lib/liferea/plugins/plugin-installer.py", line 163, in fetch_list
    resp = urllib.request.urlopen(req).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```
Alternatively turning off network produces the same error.

Feeds (ttrss) work fine with proxy so not a network issue. Tested on archlinux repo 1.13.5, flatpak 1.13.4,5

**Comment by lwindolf** [comment]
2 issues here:

- bad error handling in the python plugin manager code (error should be user visible)
- no use of proxy at all in plugin manager

**Comment by bobquest33** [comment]
Is this resolved or I can take a look

**Comment by lwindolf** [comment]
No solution yet.

**Comment by lwindolf** [comment]
Feel free to take a look!

**Comment by bbhtt** [comment]
Actually it refuses to open when no there is no internet connectivity with the same error in console, it should at least open and allow managing the installed plugins. I will edit the title to reflect that.

**Comment by lwindolf** [comment]
Plugin manager now does not fail when internet is not available.

**Comment by nasacode1** [comment]
Check Proxy Settings:

Ensure that your GNOME Control Center proxy settings are correctly configured.
Verify that the SOCKS5 proxy is working as expected on localhost:9050.
Check Ignore Hosts:

Double-check that you have entered the correct Ignore hosts: 127.0.0.0/8, ::1. This setting is important for bypassing the proxy for local addresses.
Verify Internet Connectivity:

Ensure that your internet connection is stable and working. You mentioned that Feeds (ttrss) work fine, so it's likely not an issue with your internet connection.
Check Liferea Configuration:

Make sure that Liferea is set to auto-detect the proxy.
Test Without Proxy:

Try running Liferea without the proxy to see if the Plugin Manager opens. This will help determine if the issue is related to the proxy settings.
Check for Updates:

Ensure that you are using the latest version of Liferea. Sometimes, bugs and issues are fixed in newer releases.
Community Forums or Issue Tracker:

Check if other users have reported similar issues on forums or Liferea's issue tracker. If not, consider reporting the problem.
Contact Liferea Support:

If none of the above steps resolve the issue, consider reaching out to Liferea's support or community for further assistance.

**Comment by lwindolf** [comment]
Sadly with the emergency migration to libpeas2 in #1426 the plugin installer had to be removed.

It won't get re-added for simplicity sake. For now there is only a "plugin manager" supported. All plugin installation has to be done manually. Please read more about this in the release notes of 1.16-RC3 to be released today.
